# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - "**/firebase_options.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    argument_type_not_assignable: warning
    invalid_assignment: warning
    not_iterable_spread: error
    return_of_invalid_type_from_closure: warning
    not_map_spread: warning
    avoid_dynamic_calls: warning
    field_initializer_not_assignable: warning

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    always_put_required_named_parameters_first: false
    # don't lint 80 text char limit
    lines_longer_than_80_chars: false
    # re-enable theses
    comment_references: false

# Learn more: https://dcm.dev/docs/individuals/configuration
dart_code_metrics:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - lib/generated_plugin_registrant.dart
    - lib/firebase/firebase_options.dart
  rules:
    prefer-match-file-name: false
    prefer-single-widget-per-file: false
    # TODO: avoid-unused-instances should not be disabled, but velocityX is not compatible with it
    avoid-unused-instances: false
